chore: replace obfs4 with lyrebird
This diff replaces obfs4 and uses lyrebird instead. See
https://github.com/ooni/probe-cli/pull/1347#issuecomment-1750086765
to understand why my previous assessment that we could not import
lyrebird was actually caused by PEBCAK.

The build currently fails because the set of dependencies required by
Psiphon conflict with lyrebird ones, so upgrading isn't possible.

Here is how the build fails:

```console
$ go build -v ./...
github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/protocol
/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/psiphon-tunnel-core@v1.0.11-0.20230822172011-3f91b1b804b1/psiphon/common/protocol/customTLSProfiles.go:180:16: undefined: utls.UtlsExtendedMasterSecretExtension
```

So, I think the underlying issue here may be that utls has removed
some symbols without bumping their major version number.

If it was possible to merge this work, this work would be part of
the https://github.com/ooni/probe/issues/2524 issue.