multierror: implement BuildErrorString and mark as legacy (#1587)
This diff implements BuildErrorString, which we need in
https://github.com/ooni/probe-cli/pull/1560 to construct `multierror`
compatible error strings inside the `httpclientx` package.

While there, recognize that `multierror` should now be considered legacy
(i.e., minor changes and only bugfixes) because its implementation has
`Unwrap() error` while not it would be better to use `Unwrap() []errors`
but, if we were switching to the new callback, error wrapping would find
syscall errors and use them as the result.

Therefore, an error like:

```
httpapi: all endpoints failed: [ connection_reset; connection_reset; connection_reset; connection_reset;]
```

would be reduced to:

```
connection_reset
```

Because this behavior is subtle, I think it's best to move multierror
inside `./internal/legacy` and document this.

Part of https://github.com/ooni/probe/issues/2729.